export const HardSkillsData = [
  {
    id: 1,
    skill: "HTML",
    level: 95,
    remains: 5,
    colorLevel: "#f06529",
    colorRemains: "#fcddcf",
  },
  {
    id: 2,
    skill: "CSS",
    level: 94,
    remains: 6,
    colorLevel: "#2965f1",
    colorRemains: "#b7cbfa",
  },
  {
    id: 3,
    skill: "SASS",
    level: 90,
    remains: 10,
    colorLevel: "#cc6699",
    colorRemains: "#f2d9e6",
  },
  {
    id: 4,
    skill: "JavaScript",
    level: 75,
    remains: 25,
    colorLevel: "#f0db4f",
    colorRemains: "#fbf5d0",
  },
  {
    id: 5,
    skill: "React",
    level: 75,
    remains: 25,
    colorLevel: "#61DBFB",
    colorRemains: "#cdf4fe",
  },
  {
    id: 6,
    skill: "Bootstrap",
    level: 85,
    remains: 15,
    colorLevel: "#563d7c",
    colorRemains: "#e4ddee",
  },
  {
    id: 7,
    skill: "Git, Github",
    level: 75,
    remains: 25,
    colorLevel: "#333333",
    colorRemains: "#e6e6e6",
  },
  {
    id: 8,
    skill: "Webpack",
    level: 45,
    remains: 55,
    colorLevel: "#1d78c1",
    colorRemains: "#d3e7f8",
  },
  {
    id: 9,
    skill: "Unit Testing",
    level: 70,
    remains: 30,
    colorLevel: "#86b91a",
    colorRemains: "#edf9d2",
  },
  {
    id: 10,
    skill: "Tailwind",
    level: 70,
    remains: 30,
    colorLevel: "#0ea5e9",
    colorRemains: "#cfeefc",
  },
  {
    id: 11,
    skill: "Typescript",
    level: 60,
    remains: 40,
    colorLevel: "#3399ff",
    colorRemains: "#e6f2ff",
  },
];
